name: CI/CD Pipeline

# Déclencheurs pour le pipeline : à chaque push ou pull request sur la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définition des jobs du pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16  # Spécification de la version de PostgreSQL
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: fadwa
          POSTGRES_DB: bibliotheque_iset
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Étape 1 : Cloner le code du dépôt
      - name: Checkout Code
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances du backend
      - name: Install Backend Dependencies
        run: |
          cd back
          npm install

      # Étape 3 : Installer les dépendances du frontend
      - name: Install Frontend Dependencies
        run: |
          cd front
          npm install

      # Étape 4 : Construire l'image Docker du backend
      - name: Build Backend Docker Image
        run: |
          docker build -f back/Dockerfile -t touatifadwa/backend:latest .

      # Étape 5 : Construire l'image Docker du frontend
      - name: Build Frontend Docker Image
        run: |
          docker build -f front/Dockerfile -t touatifadwa/frontend:latest .

      # Étape 6 : Se connecter à Docker Hub et pousser l'image du backend
      - name: Push Backend Docker Image
        run: |
          docker login -u touatifadwa -p foufou53550880
          docker push touatifadwa/backend:latest

      # Étape 7 : Se connecter à Docker Hub et pousser l'image du frontend
      - name: Push Frontend Docker Image
        run: |
          docker login -u touatifadwa -p foufou53550880
          docker push touatifadwa/frontend:latest

      # Étape 8 : Exécuter les tests backend (Jest)
      - name: Run Backend Tests
        env:
          DB_USER: postgres
          DB_HOST: localhost
          DB_NAME: bibliotheque_iset
          DB_PASSWORD: fadwa
          DB_PORT: 5432
          PORT: 3000
          JWT_SECRET: isettozeursecretkey
        run: |
          cd back
          npm test

      # Étape 9 : Exécuter les tests frontend (par exemple, Jest)
      - name: Run Frontend Tests
        run: |
          cd front
          npm test

      # Étape 10 : Déployer sur Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Étape 11 : Vérification de la santé des pods (health checks)
      - name: Verify Services Health
        run: |
          kubectl get pods
          if kubectl get pods > /dev/null 2>&1; then
            kubectl describe pod $(kubectl get pods -o jsonpath="{.items[0].metadata.name}")
          else
            echo "Aucun pod disponible."
          fi

      # Étape 12 : Rollback en cas d'échec
      - name: Rollback in case of Failure
        if: failure()
        run: |
          kubectl rollout undo deployment/backend
          kubectl rollout undo deployment/frontend